# Generated by Django 6.1 on 2026-08-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=255)),
                ('interface', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_packet', models.IntegerField(default=0)),
                ('pcap_file', models.FileField(blank=True, null=True, upload_to='pcaps/')),
            ],
        ),
        migrations.CreateModel(
            name='PacketRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sourceIP', models.GenericIPAddressField()),
                ('destIP', models.GenericIPAddressField()),
                ('sourcePort', models.IntegerField(blank=True, null=True)),
                ('destPort', models.IntegerField(blank=True, null=True)),
                ('protocol_type', models.CharField(max_length=20)),
                ('packet_length', models.IntegerField()),
                ('summary', models.TextField()),
                ('payload', models.TextField(blank=True, null=True)),
                ('capture_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='analyzer.capturesession')),
            ],
        ),
    ]
