# Generated by Django 6.1 on 2026-08-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('src_ip', models.GenericIPAddressField()),
                ('dest_ip', models.GenericIPAddressField()),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dest_port', models.IntegerField(blank=True, null=True)),
                ('protocol_type', models.CharField(max_length=15)),
                ('length', models.IntegerField()),
                ('payload', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
